# Generated by Django 4.2.5 on 2024-07-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionsportfit', '0017_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='especialidad',
            field=models.CharField(choices=[('Preparador físico', 'Preparador físico'), ('Nutricionista', 'Nutricionista'), ('sin datos', 'Sin datos')], default='sin datos', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='modalidad',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial'), ('sin datos', 'Sin datos')], default='sin datos', max_length=20),
        ),
    ]
