# Generated by Django 4.2.5 on 2024-07-03 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionsportfit', '0018_reserva_especialidad_reserva_modalidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='recibo_pdf',
        ),
        migrations.AddField(
            model_name='recibo',
            name='metodo_pago',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
