# Generated by Django 4.2.5 on 2024-07-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionsportfit', '0021_contratoempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosenvio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='direccion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
