# Generated by Django 4.2.5 on 2024-07-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionsportfit', '0022_alter_datosenvio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
