# Generated by Django 4.2.5 on 2024-07-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionsportfit', '0027_alter_datosenvio_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosenvio',
            name='ciudad',
            field=models.CharField(blank=True, default='Sin datos', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='codigo_postal',
            field=models.CharField(blank=True, default='Sin datos', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='direccion',
            field=models.CharField(blank=True, default='Sin datos', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='estado',
            field=models.CharField(blank=True, default='Sin datos', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='nombre_completo',
            field=models.CharField(blank=True, default='Sin datos', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='telefono',
            field=models.CharField(blank=True, default='Sin datos', max_length=20, null=True),
        ),
    ]
