# Generated by Django 4.2.5 on 2024-07-04 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacionsportfit', '0029_alter_datosenvio_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('empaquetando', 'Empaquetando'), ('en_camino', 'En Camino'), ('entregado', 'En camino a la casa')], default='empaquetando', max_length=50)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
