# Generated by Django 4.2.5 on 2024-07-04 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionsportfit', '0030_seguimientopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientopedido',
            name='pedido_id',
        ),
        migrations.RemoveField(
            model_name='seguimientopedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='seguimientopedido',
            name='venta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento_pedido', to='aplicacionsportfit.venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='pedido_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
