# Generated by Django 4.2.5 on 2024-07-04 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionsportfit', '0031_remove_seguimientopedido_pedido_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientopedido',
            name='estado',
            field=models.CharField(choices=[('empaquetando', 'Empaquetando'), ('en_camino', 'En Camino'), ('entregado', 'Entregado')], default='empaquetando', max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimientopedido',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='aplicacionsportfit.venta'),
        ),
    ]
